### ISSUE TITLE
inference的结果是一堆乱码，哪里出问题了？

### ISSUE THREAD

**Issue by CaicaiJason** [rese1f/MovieChat#12]
![image](https://github.com/rese1f/MovieChat/assets/27617518/1cf02fb1-0891-43ee-8c49-c73ef0a5772e)
python inference.py --cfg-path eval_configs/MovieChat.yaml --gpu-id 0 --num-beams 1 --temperature 1.0 --text-query "describe this video" --video-path src/examples/p1472zrh7a0.mp4 --fragment-video-path src/video_fragment/output.mp4 --cur-min 1 --cur-sec 1 --middle-video 1
出来的结果是乱码呢，大佬看看？

**Comment by Espere-1119-Song** [comment]
出现乱码可能是llm配置错误导致的

**Comment by CaicaiJason** [comment]
![image](https://github.com/rese1f/MovieChat/assets/27617518/0c82fc68-7c5f-4ce5-b736-aa91b1aedf04)
帮忙看下config这里哪里配错了呢？

**Comment by Espere-1119-Song** [comment]
config里面配置的是预训练权重的路径，出现乱码可能是权重下载的版本有问题或者在llama和vicuna权重相加时出现问题。

**Comment by tian1327** [comment]
> ![image](https://user-images.githubusercontent.com/27617518/260370235-0c82fc68-7c5f-4ce5-b736-aa91b1aedf04.png) 帮忙看下config这里哪里配错了呢？

I am having the same issue in generating random words using the Cooking_cake.mp4, did you figure out the problem? Thank you!

![image](https://github.com/rese1f/MovieChat/assets/65430862/824a3759-e36d-4031-9907-0c3f70f5be0c)

**Comment by tian1327** [comment]
@CaicaiJason Hi there, I am having the same issue in generating random words using the Cooking_cake.mp4, did you figure out the problem? Thank you!

![image](https://github.com/rese1f/MovieChat/assets/65430862/f8c06542-21a9-44ac-9ddd-72779d3efac7)

**Comment by tian1327** [comment]
@CaicaiJason I was able to figure it out. In the `MovieChat.ymal`, the `llama_model: "ckpt/Vicuna/vicuna-7b-delta-v0"` should be set to ` llama_model: "ckpt/Vicuna/7B"`

**Comment by bibibabibo26** [comment]
你好，我有个疑问，我调试代码时发现llama_proj_model没有初始化到模型里（如moviechat.MovieChat.from_config中model()传递的参数没有llama_proj_model）？请问您是否修改了这一块？如果不需要修改，则该层没有被初始化也可以跑，请问您知道原因吗？
