### ISSUE TITLE
example video可以开放下不？

### ISSUE THREAD

**Issue by renqingcolin** [rese1f/MovieChat#15]
论文里的两个example视频都挺有意思的，方便给个链接开放下吗？
src/examples/Cooking_cake.mp4
src/examples/goblin.mp4

**Comment by Espere-1119-Song** [comment]
Sure, you can download the example movies according to this [link](https://drive.google.com/drive/folders/1uvtpF8a1jWoU7YmJkW0voujW0kZFQUZ3?usp=sharing).
