### ISSUE TITLE
Inference tails

### ISSUE THREAD

**Issue by fazlicodes** [rese1f/MovieChat#19]
When I inference.py, it reaches upto this point and then the process gets killed. Can I know the reason for it? 
`Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Using pad_token, but it is not set yet.
Loading checkpoint shards:   0%|                                                                                                                                                                  | 0/2 [00:00<?, ?it/s]`

How much memory is required? I tried with 100gb RAM machine and it still failed

**Comment by Espere-1119-Song** [comment]
The information displayed indicates that you are loading the checkpoint required by MovieChat. Although it does take a long time to load the checkpoint, I have not encountered a situation where the process was killed. When I execute inference.py, the GPU required is about 16GB.
