### ISSUE TITLE
YAML file

### ISSUE THREAD

**Issue by fazlicodes** [rese1f/MovieChat#20]
In the yaml file for `llama_model` should it be the `--target` directory of the `apply_delta.py` or the `--delta`

**Comment by Espere-1119-Song** [comment]
It should be the ` --target` directory :)

**Comment by fazlicodes** [comment]
Noted, thank you. On another note what is the `--fragment-video-path` argument for inference.py?

**Comment by Espere-1119-Song** [comment]
Since the video is relatively long and cannot be read all at once, we set up a sliding window to read the video step by step. `--fragment-video-path` stores the video read by the sliding window at each time step.
