### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by fazlicodes** [rese1f/MovieChat#22]
I got the following error when running the inference script:
`Traceback (most recent call last):
  File "/home/mohamed.imam/Projects/MovieChat/inference.py", line 384, in <module>
    msg = chat.upload_video_without_audio(
  File "/home/mohamed.imam/Projects/MovieChat/inference.py", line 277, in upload_video_without_audio
    video_emb, _ = self.model.encode_long_video(cur_image, middle_video)
  File "/home/mohamed.imam/Projects/MovieChat/MovieChat/models/moviechat.py", line 337, in encode_long_video
    cur_short = torch.cat(self.temp_short_memory, dim = 0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors`

I skipped the cur_short assignment line of code, but in the next line the variable `video_features` is used before assignment:
            if len(self.long_memory_buffer) == 0:
                self.temp_short_memory = [i.unsqueeze(0) for i in self.temp_short_memory]
                cur_short = torch.cat(self.temp_short_memory, dim = 0)
                video_features = torch.cat([video_features, cur_image], dim = 0)
            else:
                cur_video = torch.cat(self.long_memory_buffer,dim = 0)
                self.temp_short_memory = [i.unsqueeze(0) for i in self.temp_short_memory]
                cur_short = torch.cat(self.temp_short_memory, dim = 0)
                video_features = torch.cat([cur_video,cur_short], dim = 0)
                video_features = torch.cat([video_features, cur_image], dim = 0)

**Comment by Espere-1119-Song** [comment]
Thank you for your interest in our work. I have noted this error when I reorganized my code, I have come across this issue and the updated code will be released later. You can try the solution in [Issue 18](https://github.com/rese1f/MovieChat/issues/18).

**Comment by fazlicodes** [comment]
Noted, I will try that and see

**Comment by fazlicodes** [comment]
@Espere-1119-Song but the code provide in Issue 18 doesn't handle the issue that I'm talking about

**Comment by fazlicodes** [comment]
@Espere-1119-Song @rese1f @rejoicelf is it possible for me know when will the updated code be release?

**Comment by Espere-1119-Song** [comment]
The code will be release in November.Can you provide your config and script used for inference?

**Comment by fazlicodes** [comment]
That's great. Here are the links for the config file and the inference script I used.
https://drive.google.com/file/d/1mymf9iECaLonuTMFirVYVaWoI6AgCMTG/view?usp=share_link
https://drive.google.com/file/d/17tR7XR32eGWBFIhjWnf5K2h3a4FZzwSz/view?usp=share_link

**Comment by Espere-1119-Song** [comment]
Thanks，can you provide the instruction you used for inference and the input video if available?

**Comment by fazlicodes** [comment]
The instruction was "What is happening in this video?"
The video link https://drive.google.com/file/d/1mq1uC12goZBiWcKVY0YUK5vVoFT4qAdM/view?usp=share_link

**Comment by Espere-1119-Song** [comment]
I've updated [moviechat.py](https://github.com/rese1f/MovieChat/blob/main/MovieChat/models/moviechat.py) to what I'm using now. The current version of the code can run on my computer with llama7b. The command executed by inference is as follows:
```
python inference.py \
    --cfg-path eval_configs/MovieChat.yaml \
    --gpu-id 0 \
    --num-beams 1 \
    --temperature 1.0 \
    --text-query "What is happening in this video?" \
    --video-path src/examples/terminator.mp4 \
    --fragment-video-path src/video_fragment/output.mp4 \
    --cur-min 1 \
    --cur-sec 1 \
    --middle-video 0 \
```
The answer was as follows:
```
In the given video, we can see a series of scenes of a post-apocalyptic world with ruins of buildings, debris, and rubble. We can also see a train, a ship, a statue, and a tank. Throughout the video, we see different people in the scene, including a woman holding a camera, a man on a boat, a man and a woman, a man and woman walking, and a man standing by a train. Additionally, we see a blue sky, a moon, and various objects such as a gun, a bike, a tree, and a stone.
```

In addition, we welcome you to use longer videos (for example, videos of about 10 minutes) for testing.

**Comment by fazlicodes** [comment]
Thank you @Espere-1119-Song , I really appreciate your prompt responses. 
But even after updating the moviechat.py with the latest code. I'm getting the following error when I use same inference as above:
`Traceback (most recent call last):  
  File "/l/users/sanoojan.baliah/Felix/MovieChat/inference.py", line 393, in <module>
    msg = chat.upload_video_without_audio(
  File "/l/users/sanoojan.baliah/Felix/MovieChat/inference.py", line 294, in upload_video_without_audio
    video_emb, _ = self.model.encode_long_video(cur_image, middle_video)
  File "/l/users/sanoojan.baliah/Felix/MovieChat/MovieChat/models/moviechat.py", line 336, in encode_long_video
    cur_short = torch.cat(self.temp_short_memory, dim = 0)`

**Comment by Espere-1119-Song** [comment]
Sorry, I have no idea about the error since I did not meet it. Maybe you can try it after I reorganize the code.

**Comment by fazlicodes** [comment]
Noted, thank you. I'm eagerly waiting for you to release the reorganized code.

**Comment by fazlicodes** [comment]
Hi @Espere-1119-Song , when will the latest code and paper be uploaded?

**Comment by Espere-1119-Song** [comment]
within two week.
