### ISSUE TITLE
Did not find video Cooking_cake.mp4

### ISSUE THREAD

**Issue by jasmine-ww** [rese1f/MovieChat#23]
Hi! I am trying to run the demo, but I cannot find the video src/examples/Cooking_cake.mp4. Could you please upload the video?

**Comment by Espere-1119-Song** [comment]
Since the video is too big to upload, you can download the example movies according to this [link](https://drive.google.com/drive/folders/1uvtpF8a1jWoU7YmJkW0voujW0kZFQUZ3?usp=sharing).
