### ISSUE TITLE
Is positional embedding applied as intended when batch_size > 1

### ISSUE THREAD

**Issue by minostauros** [rese1f/MovieChat#25]
The codes are assuming batch_size == 1 so it wouldn't be a big deal, but the code is misleading.

Reproducing the pos emb expansion in MovieChat could be:

```python
video_frame_position_embedding = nn.Embedding(max_frame_pos, self.Qformer.config.hidden_size) # [32,768]
n_position = 8
position_ids = torch.arange(n_position).long() # [8]
position_ids = position_ids.unsqueeze(0).expand(batch_size, -1) # [batch_size, 8]
p = video_frame_position_embedding(position_ids).squeeze(0) # [batch_size, 8, 768] <- squeeze does not have any effect here if batch_size > 1

u = []
alpha = 0.01 

for p_i in p: # <- this loops through batch_size, so all p_i are identical
    u_i = (p_i-alpha * p[0])/(1-alpha)
    u.append(u_i)
# so here, all u_i are identical, e.g., torch.all(u[0] == u[1]) is True

frame_position_embeddings = []
for i in range(n_position):
    for j in range(n_position):
        q_i = alpha * u[i] + (1-alpha) * u[j] # if 1 < batch_size < n_position, index error occurs here
        q_i = q_i.unsqueeze(0)
        frame_position_embeddings.append(q_i)

frame_position_embeddings = torch.cat(frame_position_embeddings, dim = 0)
```

In addition, if the `self.video_frame_position_embedding` is fixed, why do we need to compute `frame_position_embeddings` for every inference?

**Comment by Espere-1119-Song** [comment]
`self.video_frame_position_embedding` is loaded from pretrained model, which is not long enough for long-term memory encoding,thus we need to expand the frozen `self.video_frame_position_embedding`. More details in the  [https://arxiv.org/abs/2307.16449](paper).

**Comment by minostauros** [comment]
I know why you're expanding the positional embeddings, I'm asking about possibly inadequate implementation.

**Comment by Espere-1119-Song** [comment]
Thanks a lot, I will fix it next version too.
