### ISSUE TITLE
Token Merging

### ISSUE THREAD

**Issue by insafim** [rese1f/MovieChat#28]
So when you compare x1 with x2 it is mentioned in equation (3) that you compare N tokens and get the average.
My question is x1 has a shape of CxNxD. So doesn't it have CxN number of tokens to compare with x2?

**Comment by Espere-1119-Song** [comment]
Sorry, there are some problems with the expression of some formulas in the current paper. Actually, x1 denotes one frame feature with the shape of NxD, and we calculate N tokens similarity and get the average.

**Comment by insafim** [comment]
Okay, thanks for the clarification.
