### ISSUE TITLE
About short_memory_merge and long_memory_length

### ISSUE THREAD

**Issue by liziming5353** [rese1f/MovieChat#32]
From conference.py, it can be seen that in the "encode_short_memory_frame" function, short_memory_merge is used to merge, however, long_ memory_length parameter looks more like the RL mentioned in the paper, but it is not used. May I ask if you can provide a detailed explanation of the operation process of the memory network? For example, in the form of pseudocode or algorithms. The expression in the paper and code really confuses me.

**Comment by Espere-1119-Song** [comment]
`short_memory_merge ` is set to 2 in [MovieChat](https://github.com/rese1f/MovieChat/tree/main/MovieChat)/[models](https://github.com/rese1f/MovieChat/tree/main/MovieChat/models)/moviechat.py, which stands for R_{L} in the paper. 

Please make sure the paper version first: https://arxiv.org/pdf/2307.16449.pdf

For the detailed explanation of the operation process of memory consolidation, you can refer to **Section 3.4. Long-term Memory** in the paper. For the pseudocode, you can refer to **Algorithm 1 Memory consolidation** in page 4. For the algorithm schematic diagram， **Figure 2. in page 3** and **Figure A1. in page 14** may help a lot. 

Hope the information I provide can help clarify your confusion.

**Comment by Espere-1119-Song** [comment]
Yes, and the implement details and the result of the experiment can be seen in **Section 5.2. Ablation Study**, which signifies the importance of memory mechanisms.

**Comment by liziming5353** [comment]
Where are the paramter long_memory_length and the function encode_videoQformer_visual used?

**Comment by Espere-1119-Song** [comment]
In fact, they were not used.

**Comment by liziming5353** [comment]
Is the length of the long memory unrestricted in this way? Figure 1 in the paper shows that VRAM occupancy remains constant, which seems to be due to the length of the long memory being set.

**Comment by Espere-1119-Song** [comment]
The length of the long memory is indeed unrestricted. There is a minor variation in VRAM for MovieChat, and **it is independent of the setting of the long memory length.** The reason for the minimal variation in RAM usage in our method is that **our memory consolidation strategy effectively conserves RAM while preserving video information as much as possible.**

**Comment by liziming5353** [comment]
Have you estimated how many frames and tokens a video will ultimately retain? If a video is very long, will it exceed the input limit of a large language model?

**Comment by Espere-1119-Song** [comment]
the input limit of LLaMA is 256, so after memory consolidation, the final retained frames is no more than 256 ( in global modal, it will retain 256 frames in the long-term memory)

**Comment by liziming5353** [comment]
但是我看到vicuna的输入长度是4k？这个长度是不是token数量而不是帧数呀。如果图片是224*224并且patch=14的话，每一帧的token数应该是256吧
