### ISSUE TITLE
Question About Similarity Formulation in Token Merge

### ISSUE THREAD

**Issue by zhang9302002** [rese1f/MovieChat#34]
Hello, in your paper the similarity is calculated as: 
$$s=\frac{1}{N}\sum_{j=1}^{N} [\cos (x_i^j,x_{i+1}^j)]$$

However, according to [this_code](https://github.com/rese1f/MovieChat/blob/main/MovieChat/models/moviechat.py#L301),
the similarity is calculated indeed as:
$$s=\frac{1}{N^2}\sum_{j=1}^{N} \sum_{k=1}^{N} [\cos (x_i^j,x_{i+1}^k)]$$

It confused me. Which one is the right case, or do I miss some information? Thank you.

**Comment by Espere-1119-Song** [comment]
$i$ stands for the $i$-th frames, and $j$ stands for the token index，aiming to calculating the average similarity of each respective tokens between two frames. The specific similarity calculating code is referred to TOME.

**Comment by zhang9302002** [comment]
Your code calculates the average similarity of all token pairs between two frames $(x^j, y^k)$, instead of each respective pairs $(x^j, y^j)$. I think this contradicts with the paper.

**Comment by Espere-1119-Song** [comment]
Thanks for your valuable advise and we have fixed the bug in our code. The current code also provides the same result of our paper.
