### ISSUE TITLE
Unable to access LLaMA weights to build Vicuna-7B

### ISSUE THREAD

**Issue by muzairkhattak** [rese1f/MovieChat#36]
Dear Team,

Thank you for sharing this great work with the community.

I am trying to set up the inference model for videochat but I am having difficulties in downloading the official LLaMA 7b weights as they are not officially available from meta.

The provided links in below instruction do not provide for LLaMA 1 models. We can only download llama 2 models from the below links.

Get the original LLaMA weights in the Hugging Face format by following the instructions [here](https://huggingface.co/docs/transformers/main/model_doc/llama).

Could you upload the llama 7b and llama 13b weights so we can directly utilize them?

Thank you in advance!

Kind regards,
Muhammad Uzair

**Comment by Espere-1119-Song** [comment]
Sorry, due to copyright issues, we cannot upload the weight files for LLaMA 7B and 13B. You can try using the official authentication method provided to obtain the weights. Additionally, the weights for LLaMA2 are also applicable to MovieChat, and no modifications are needed in the code.

**Comment by muzairkhattak** [comment]
No problem! I was able to download the weights [from this repo. ](https://github.com/juncongmoo/pyllama)
