### ISSUE TITLE
No main funciton in inference.py

### ISSUE THREAD

**Issue by wanghao-cst** [rese1f/MovieChat#4]
Dear author, 

When I try to infer the model, it seems nothing happens.

**Comment by Espere-1119-Song** [comment]
Can you describe it in more detail? Such as error messages or screenshots. If you can see the progress bar for video processing, but there is no output in the end, it may be caused by a wrong configuration of the text decoder.

**Comment by wanghao-cst** [comment]
> Can you describe it in more detail? Such as error messages or screenshots. If you can see the progress bar for video processing, but there is no output in the end, it may be caused by a wrong configuration of the text decoder.

There is an error showing this.
<img width="903" alt="截屏2023-08-03 21 49 56" src="https://github.com/rese1f/MovieChat/assets/55015183/63e6b739-d38e-443b-97d2-ca3951113ff5">

Then, I comment on https://github.com/rese1f/MovieChat/blob/main/inference.py#L26
There is no error, but the terminal only shows some warning witho
<img width="904" alt="截屏2023-08-03 21 52 40" src="https://github.com/rese1f/MovieChat/assets/55015183/8ed3225a-41be-44bd-aa0b-522ce3b86082">
ut any other process.

**Comment by Espere-1119-Song** [comment]
I updated the inference.py, you can try again with the updated one.

**Comment by wanghao-cst** [comment]
> I updated the inference.py, you can try again with the updated one.

Thank you for your help, but there is an error:
<img width="993" alt="截屏2023-08-04 10 07 43" src="https://github.com/rese1f/MovieChat/assets/55015183/fd3d4eaa-e716-4d15-ba4c-73fd5567ae78">

**Comment by Espere-1119-Song** [comment]
It seems error with temp_frame_path. 
Check if the path exists. 
If it still doesn't work, try to temporarily use a picture as snap_shot.jpg, and  function imwrite will overwrite it with the correct snapshot.

**Comment by wanghao-cst** [comment]
> It seems error with temp_frame_path. Check if the path exists. If it still doesn't work, try to temporarily use a picture as snap_shot.jpg, and function imwrite will overwrite it with the correct snapshot.

Solved, please make sure the input video length is long enough for the infer argument.
