### ISSUE TITLE
Using pad_token, but it is not set yet.

### ISSUE THREAD

**Issue by DITINGmisa** [rese1f/MovieChat#43]
When I run the inference.py, it shows me "Using pad_token, but it is not set yet." Then I have to wait a few minutes. Is that a normal phenomenon？
![image](https://github.com/rese1f/MovieChat/assets/79569006/dbba15c2-1f1e-4320-8f6a-50fc1f08cdcb)

**Comment by Espere-1119-Song** [comment]
sure, it wil take a long time to load checkpoint shards

**Comment by DITINGmisa** [comment]
ok, thank you : )
