### ISSUE TITLE
errors when using the global mode

### ISSUE THREAD

**Issue by tianguang2525** [rese1f/MovieChat#44]
when using the global mode, how to set the parameter?
I set:
"--cfg-path", "eval_configs/MovieChat.yaml",
                "--gpu-id", "0",
                "--num-beams", "1" ,
                "--temperature", "1.0" ,
                "--text-query", "Summarize the video" ,
                "--video-path", "/home/develop/fyy/MovieChat-main/src/examples/11.mp4" ,
                "--fragment-video-path", "src/video_fragment/output.mp4" ,
                "--cur-min", "0" ,
                "--cur-sec", "0" ,
                "--middle-video", "0" 
but 
![微信图片_20240308214844](https://github.com/rese1f/MovieChat/assets/63250385/59c93860-648c-4950-b2bd-81df7ee58fc1)

**Comment by Espere-1119-Song** [comment]
fragment-video-path no need to be NULL. Can u print the video_path in line 240 and check if the video_path exists? Or do u have the root to access the video_path?

**Comment by tianguang2525** [comment]
> fragment-video-path no need to be NULL. Can u print the video_path in line 240 and check if the video_path exists? Or do u have the root to access the video_path?

In line 240, video_path='/home/develop/fyy/MovieChat-main/src/examples/11.mp4'

**Comment by Espere-1119-Song** [comment]
'ffprobe' is just a setting for calculating video duration and it has no relations with 'path'.

**Comment by tianguang2525** [comment]
已解决，我没有安装ffprobe,感谢！
