### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by wanghao-cst** [rese1f/MovieChat#6]
Awesome work!
Will you share the training or fintuning code?

**Comment by rese1f** [comment]
Thank you for your insterest, please see the closed issue #2   
_"Our method is training-free, you can implement this mechanism in any model."_

**Comment by wanghao-cst** [comment]
> Thank you for your insterest, please see the closed issue #2 _"Our method is training-free, you can implement this mechanism in any model."_

Thank you for the reply.
May I know what is the baseline of model part?
It seems like MiniGPT-4. In the paper it illustrates a lot of MLLM.

**Comment by rese1f** [comment]
We build our model based on video-llama, since it is a simple but strong **video-based** MLLM.

**Comment by wanghao-cst** [comment]
Thank you.
