### ISSUE TITLE
Questions about the MovieChat_1K_test

### ISSUE THREAD

**Issue by hmxiong** [rese1f/MovieChat#63]
Great work! This work is exciting and meaningful.
I found that the published test data in https://huggingface.co/datasets/Enxin/MovieChat-1K-test does not contain the "right answer", but the eval process requires it.  How can I solve it?
<img width="585" alt="image" src="https://github.com/rese1f/MovieChat/assets/74129781/aa703031-5fe4-4661-91d2-60be8164cce0">

**Comment by Espere-1119-Song** [comment]
We are holding a challenge in CVPR2024 LOVEU [Workshop.](https://codalab.lisn.upsaclay.fr/competitions/18284?secret_key=bd5e312c-4775-43cf-933b-70726d00bcbe) For a fair competition, we will not release the ground truth of the test set before the competition finish (around June 9th).

**Comment by hmxiong** [comment]
Got it！Thank you.
