### ISSUE TITLE
Inquery about the release of the validation set

### ISSUE THREAD

**Issue by patrick-tssn** [rese1f/MovieChat#66]
Thank you for your work, when will you release the validation set?

**Comment by Espere-1119-Song** [comment]
the videos of the validation set have been released, and the json files will be released after our CVPR2024 LOVEU workshop challenge (about 1-2 weeks).

**Comment by patrick-tssn** [comment]
Thank you for your quick reply, the evaluation pipeline for the workshop seems broken.

`python: can't open file '/tmp/codalab/tmpKqYi3w/run/$scoring_program/evaluate.py': [Errno 2] No such file or directory`

**Comment by Espere-1119-Song** [comment]
please ignore it. once you submit your results, we will receive and evaluate

**Comment by patrick-tssn** [comment]
How can I get the result? Will this submission (status: failed) be considered a valid attempt and count towards the quota?

**Comment by Espere-1119-Song** [comment]
we will email you. 

the failed submission will be considered a valid attempt and count towards the quota too.

**Comment by patrick-tssn** [comment]
Thank you for your reply.
