### ISSUE TITLE
Annotations and videos for the validation set + json file formatting issue

### ISSUE THREAD

**Issue by joslefaure** [rese1f/MovieChat#69]
Thanks for opensourcing the dataset. I was to exploring using it our work and notice the evaluation videos are not available (or maybe not labelled as such), could you please enlighten me?

Another issue I encounter has to do with the wrong formatting of some json files. [This one](https://huggingface.co/datasets/Enxin/MovieChat-1K_train/blob/main/jsons/S02E2-1.json), for example has a captions that goes like this `"caption": ""Do you know Dartmoor?" He is asked..."`. The double quote inside the double quote should be formatted as `"caption": "\"Do you know Dartmoor?\" He is asked..."` otherwise the python json library cannot open them. Could you please help fix that? 
Thank you for taking the time

**Comment by Espere-1119-Song** [comment]
evaluation videos is available via https://huggingface.co/datasets/Enxin/MovieChat-1K-test/tree/main

thanks for your point out, we will fix it in the next version of our dataset.
