### ISSUE TITLE
Question about dataset split?

### ISSUE THREAD

**Issue by xuzq23** [rese1f/MovieChat#77]
Great work!
I see that 1,000 videos were split into training/validation/test set (800/100/100) in the paper, while [training](https://huggingface.co/datasets/Enxin/MovieChat-1K_train)/[test](https://huggingface.co/datasets/Enxin/MovieChat-1K-test) set (830/170) in the HuggingFace differently. 
Which setting should I use to get the results in the paper?

**Comment by Espere-1119-Song** [comment]
Thanks for your attention! You can use the test set on huggingface to get the similar result.
