### ISSUE TITLE
Adjust hyperparameters of MovieChat-Plus after training

### ISSUE THREAD

**Issue by oximi123** [rese1f/MovieChat#80]
Hello, is it still possible to adjust the hyperparameter of MovieChat-Plus, like Length of Memory Buffer and the Question-frame Similarity Threshold during the inference phase? I just want to investigate the effectiveness of each hyperparamter without retraining the model.

**Comment by Espere-1119-Song** [comment]
sure, MovieChat++ is still training-free. You can modify the hyperparameter directly.
